// <auto-generated />
using Banco3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Banco3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Banco3.Models.Financial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Financial");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "001",
                            Price = 200.00m,
                            ProductCode = "001"
                        },
                        new
                        {
                            Id = 2,
                            Code = "002",
                            Price = 100.00m,
                            ProductCode = "002"
                        },
                        new
                        {
                            Id = 3,
                            Code = "003",
                            Price = 1200.00m,
                            ProductCode = "003"
                        },
                        new
                        {
                            Id = 4,
                            Code = "004",
                            Price = 5100.00m,
                            ProductCode = "004"
                        },
                        new
                        {
                            Id = 5,
                            Code = "005",
                            Price = 11100.00m,
                            ProductCode = "005"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
