// <auto-generated />
using Banco2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Banco2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Banco2.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "001",
                            CustomerCode = "001",
                            Name = "Internet Fibre 600M"
                        },
                        new
                        {
                            Id = 2,
                            Code = "002",
                            CustomerCode = "002",
                            Name = "Internet Fibre 500M"
                        },
                        new
                        {
                            Id = 3,
                            Code = "003",
                            CustomerCode = "003",
                            Name = "Cloud"
                        },
                        new
                        {
                            Id = 4,
                            Code = "004",
                            CustomerCode = "004",
                            Name = "Server to Data Center"
                        },
                        new
                        {
                            Id = 5,
                            Code = "005",
                            CustomerCode = "005",
                            Name = "Satélite"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
